language: python

os:
  - linux

sudo: required
dist: trusty
group: edge

notifications:
    email: false

git:
  depth: 10

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin

before_install:
  # Need Cython for generating C/python wrapper
  - pip install --upgrade pip
  - pip install Cython
  - pip install mpi4py
  - pip install matplotlib

  # Setup directory structure
  - INSTALL_PREFIX=/home/$USER
  - PAROPT_PATH=INSTALL_PREFIX=/home/$USER/paropt
  - export PYTHONPATH=${PYTHONPATH}:PAROPT_PATH
  - mkdir -p $INSTALL_PREFIX/git
  - cd $INSTALL_PREFIX/git

install: 
  - git clone https://github.com/gjkennedy/paropt.git
  - cd paropt
  - cp Makefile.in.info Makefile.in
  - make
  
  # Currently assume inplace installation and setting python path
  - make interface

script: 
  - python examples/python/toy.py
  - mpirun -np 2 python examples/python/toy.py
  - cd $INSTALL_PREFIX/git/paropt/examples/rosenbrock/; make; mpirun -np 8 ./rosenbrock; cd -;